name: Validate Branch Name
description: Validates that the name of a branch associated with a PR is usuable to predict the next version of the repo.
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Setup Launch-CLI
      shell: bash
      run: |
        python3 -m pip install launch-cli

    - name: Validate Branch Name
      shell: bash
      run: |
        launch validate branch-name --branch-name $GITHUB_HEAD_REF
    
    - name: Check Repository Labels
      shell: bash
      run: |
        launch github repo check-labels --repository-name ${{ github.event.repository.name }} || launch github repo create-labels --repository-name ${{ github.event.repository.name }}

    - name: Apply PR Labels
      shell: bash
      run: |
        launch github repo label-pull-request --repository-name ${{ github.event.repository.name }} --pull-request-id ${{ github.event.number }}
